services:
  postgres:
    image: postgres:15
    container_name: diet-db
    environment:
      POSTGRES_DB: dietdb
      POSTGRES_USER: dietuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: diet-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dietdb
      SPRING_DATASOURCE_USERNAME: dietuser
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  pgdata:

