### Get request
GET http://localhost:8080/api/ingredient

###
POST http://localhost:8081/api/ingredient;
Content-Type: application/json

{
  "name": "chicken",
  "calories": 999,
  "fat": 7,
  "protein": 17,
  "carbs": 66
}

