### Get all recipes
GET http://localhost:8080/api/v1/recipe
Accept: application/json

###

### Get recipe by ID
GET http://localhost:8080/api/v1/recipe/id/3
Accept: application/json

###

### Get recipe by name
GET http://localhost:8080/api/v1/recipe/name/Quinoa Bowl
Accept: application/json

###

### Get recipe(s) by diet ID
GET http://localhost:8080/api/v1/recipe/diet-id/5
Accept: application/json

###

### Get recipe(s) by diet name
GET http://localhost:8080/api/v1/recipe/diet-name/Keto
Accept: application/json

###

### Create a new recipe (admin only)
POST http://localhost:8080/api/v1/recipe
Content-Type: application/json

{
  "name": "Tuna poke",
  "dietId": 5
}

###

### Update existing recipe by ID (admin only)
PUT http://localhost:8080/api/v1/recipe/1
Content-Type: application/json

{
  "name": "Updated Quinoa Bowl",
  "dietId": 3
}

###

### Delete recipe by ID (admin only)
DELETE http://localhost:8080/api/v1/recipe?id=8
